[package]
name = "sensei-values"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sensei-core.workspace = true
sensei-parser.workspace = true
hashbrown.workspace = true
alloy-primitives.workspace = true
