[package]
name = "sensei-mir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sensei-core.workspace = true
sensei-types.workspace = true

alloy-primitives.workspace = true
