[package]
name = "sir-debug-backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sensei-core.workspace = true
sir-data.workspace = true
sir-assembler.workspace = true
alloy-primitives.workspace = true
smallvec.workspace = true
