[package]
name = "sensei-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
allocator-api2.workspace = true
alloy-primitives.workspace = true
bumpalo.workspace = true
hashbrown.workspace = true


